### ISSUE TITLE
Avoid duplicate naming

### ISSUE THREAD

**Issue by owlas** [lightdash/dbt2looker#25]
If a user regularly uses the column name as the metric name, the yaml spec becomes quite repetitive, can we make this any easier?

e.g.
```
        - name: NewCustPromoCost_USD
          description: "Total customers Promo Type Cost in USD."
          meta:
           measures:
             NewCustPromoCost_USD:
               type: sum
           dimension:
            enabled: false

```
