### ISSUE TITLE
Support model level measures

### ISSUE THREAD

**Issue by yu-iskw** [lightdash/dbt2looker#50]
## Motivation
We technically implement a measure with multiple columns under a column meta. But, it would be more natural to implement such measures as model-level.

```
models:
  - name: ubie_jp_lake__dm_medico__hourly_score_for_nps
    description: |
      {{ doc("ubie_jp_lake__dm_medico__hourly_score_for_nps") }}
    meta:
      measures:
        total_x_y_z:
          type: number
          description: 'Summation of total x, total y and total z'
          sql: '${total_x} + ${total_y} + ${total_z}'

```
